### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by dko1905** [gufranthakur/CodeLite#1]
There's no guide in the README.

After running `mvn clean package` and running the compiled jar, I get the following error:
```sh
daniel@fedora:/tmp/CodeLite$ java -jar ./target/CodeLite-1.0-SNAPSHOT.jar 
no main manifest attribute, in ./target/CodeLite-1.0-SNAPSHOT.jar
```

**Comment by PrethamMuthappa** [comment]
@dko1905  your issue can be fixed by adding this plugin to pom.xml

**Comment by dko1905** [comment]
Jep, #2 fixes the issue.
